@rootUrl = http://localhost:8000/api/customer/v1

### SIGNUP REQUEST
POST {{rootUrl}}/auth/signup
Content-Type: application/json

{
  "fName": "bibek",
  "lName": "hamal",
  "email": "bbekhamal26@gmail.com",
  "password": "Password123"
}


###verify the user and activate
GET {{rootUrl}}/auth/activate-user?sessionId=689d60c72ab2e01a9a9bb2c6&t=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QxMjM0NUBleGFtcGxlLmNvbSIsImlhdCI6MTc1NTE0NDM5MCwiZXhwIjoxNzU1MTQ1MjkwfQ.neDFjLlNsSIx7UFntelvTKaBF7a_KBcAE1XpZOpwXoA

POST {{rootUrl}}/auth/login
Content-Type: application/json

{
  "email": "test12@example.com",
  "password": "Password"
}

###get user profile

GET {{rootUrl}}/auth/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QxMkBleGFtcGxlLmNvbSIsImlhdCI6MTc1NDg4NTA4NywiZXhwIjoxNzU0OTcxNDg3fQ.tcgBsnp_SoqZjw99NFIT6i5WVNHRIFFsFV06pWvc9cE

###generate the otp
POST {{rootUrl}}/auth/otp
Content-Type:  application/json 

{
  "email": "test12@example.com"
}


###reseting the password

POST {{rootUrl}}/auth/reset-password
Content-Type: application/json

{
    "email": "test12@example.com",
  "password": "Password1234",
  "otp":7850
}

### TEST PRODUCTS
GET {{rootUrl}}/products?page=1





### GET SINGLE PRODUCT
GET {{rootUrl}}/products/688190b476f081edb92f8938


### GET ALL CATEGORIES
GET {{rootUrl}}/categories

### PLACE ORDER 
POST {{rootUrl}}/orders
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlczFAZXhhbXBsZS5jb20iLCJpYXQiOjE3NTI2Mjk2MzMsImV4cCI6MTc1MjcxNjAzM30.N3sB_Nke8W-Xl1kAzOwuRd8VX-LZmyt0n9fB2hqDz-w

{
  "products": [
    {
      "productId": "6876f89651a0344d0fb9f059",
      "quantity": 1
    }
  ],
  "totalAmount": 2499
}

###GET MY ORDERS##
GET {{rootUrl}}/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlczFAZXhhbXBsZS5jb20iLCJpYXQiOjE3NTI2Mjk2MzMsImV4cCI6MTc1MjcxNjAzM30.N3sB_Nke8W-Xl1kAzOwuRd8VX-LZmyt0n9fB2hqDz-w


###sumit a review##

### 1. SUBMIT A REVIEW (logged-in user)
POST {{rootUrl}}/reviews
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlczFAZXhhbXBsZS5jb20iLCJpYXQiOjE3NTI2Mjk2MzMsImV4cCI6MTc1MjcxNjAzM30.N3sB_Nke8W-Xl1kAzOwuRd8VX-LZmyt0n9fB2hqDz-w

{
  "productId": "6876f89651a0344d0fb9f059",
  "rating": 5,
  "comment": "Absolutely loved this product!"
}


