@rootUrl = http://localhost:3000/api/customer/v1/auth

### SIGNUP REQUEST
POST {{rootUrl}}/signup
Content-Type: application/json

{
  "fName": "test2",
  "lName": "test1",
  "email": "tes2@example.com",
  "password": "Password123"
}


### verify 

GET {{rootUrl}}/verify/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlczJAZXhhbXBsZS5jb20iLCJpYXQiOjE3NTIwMjQ5ODksImV4cCI6MTc1MjAyNTg4OX0.qsTFN2xoZ7FN1fs31Ixe9I6c3MCgD2vttgb7gheOUHI



### LOGIN – verified user
POST {{rootUrl}}/login
Content-Type: application/json

{
  "email": "tes2@example.com",
  "password": "Password123"
}